# Generated by Django 4.1.4 on 2023-01-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='subjects')),
                ('coordinates_x', models.IntegerField()),
                ('coordinates_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Timings',
            new_name='Timing',
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('timing', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='TimeTable.timing')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.subject')),
            ],
        ),
    ]
