# Generated by Django 4.1.4 on 2022-12-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0002_monday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timings',
            new_name='Timing',
        ),
    ]
