# Generated by Django 4.1.4 on 2023-01-01 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0007_timetable_remove_tuesday_timing_delete_monday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.CreateModel(
            name='Saturday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.CreateModel(
            name='Sunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.CreateModel(
            name='Thursday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.CreateModel(
            name='Tuesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.CreateModel(
            name='Wednesday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('class_image', models.ImageField(upload_to='Class_Images')),
                ('record_class', models.BooleanField(default=False)),
                ('save_screenshot', models.BooleanField(default=False)),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='TimeTable.timing')),
            ],
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
